# Generated by Django 5.0.6 on 2024-09-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criterio', models.CharField(choices=[('Binário', 'Binário'), ('CMMI', 'CMMI'), ('Conformidade', 'Conformidade')], max_length=20)),
                ('excel_file', models.FileField(upload_to='')),
                ('data_upload', models.DateField(auto_now_add=True)),
                ('is_proprio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=255)),
                ('codCatecoria', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('controle', models.CharField(max_length=255)),
                ('diretrizes', models.TextField()),
                ('prioControle', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=255)),
                ('comentarios', models.TextField()),
                ('meta', models.CharField(max_length=255)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isos', to='assessment.meumodelo')),
            ],
        ),
        migrations.CreateModel(
            name='CisControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idControle', models.IntegerField()),
                ('controle', models.CharField(max_length=255)),
                ('tipoAtivo', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
                ('idSubConjunto', models.IntegerField()),
                ('subConjunto', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('resultado', models.CharField(max_length=255)),
                ('comentarios', models.TextField()),
                ('meta', models.CharField(max_length=255)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cis_controls', to='assessment.meumodelo')),
            ],
        ),
        migrations.CreateModel(
            name='NistCsf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('subcategoria', models.CharField(max_length=255)),
                ('informacao', models.TextField()),
                ('nota', models.CharField(max_length=255)),
                ('comentarios', models.TextField()),
                ('meta', models.CharField(max_length=255)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nist_csfs', to='assessment.meumodelo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanilhaGenerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idControle', models.IntegerField()),
                ('controle', models.CharField(max_length=255)),
                ('idSubControle', models.IntegerField()),
                ('subControle', models.CharField(max_length=255)),
                ('funcaoSeguranca', models.CharField(max_length=255)),
                ('tipoAtivo', models.CharField(max_length=255)),
                ('informacoesAdicionais', models.TextField()),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilhas_genericas', to='assessment.meumodelo')),
            ],
        ),
    ]
