# Generated by Django 5.0.6 on 2024-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criterio', models.CharField(choices=[('Binário', 'Binário'), ('CMMI', 'CMMI'), ('Conformidade', 'Conformidade')], max_length=20)),
            ],
        ),
    ]
