# Generated by Django 5.0.6 on 2024-10-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAcaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_assess', models.DateField()),
                ('acoes_cad', models.IntegerField()),
                ('custo_estimado', models.FloatField()),
                ('conclusao', models.FloatField()),
                ('status', models.CharField(choices=[('Concluído', 'Concluído'), ('Andamento', 'Andamento'), ('Iniciar', 'Iniciar')], max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_acao_model', to='assessment.assessmentmodel')),
            ],
        ),
    ]
