# Generated by Django 5.0.6 on 2024-09-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_ciscontrol_upload_id_iso_upload_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meumodelo',
            name='excel_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
