# Generated by Django 5.0.6 on 2024-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_cadplanodeacaomodel_fim_pla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadplanodeacaomodel',
            name='fim_pla',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadplanodeacaomodel',
            name='fim_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadplanodeacaomodel',
            name='inicio_pla',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadplanodeacaomodel',
            name='inicio_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
