# Generated by Django 5.0.6 on 2024-12-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_alter_cadplanodeacaomodel_fim_pla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadplanodeacaomodel',
            name='projeto',
            field=models.CharField(choices=[('Governança e Estratégia', 'Governança e Estratégia'), ('Gestão de Riscos', 'Gestão de Riscos'), ('Gestão de Terceiros', 'Gestão de Terceiros'), ('Privacidade', 'Privacidade'), ('Gestão de Identidade e Acessos', 'Gestão de Identidade e Acessos'), ('Gestão de Ativos', 'Gestão de Ativos'), ('Security Mobile (computadores e celulares)', 'Security Mobile (computadores e celulares)'), ('Cloud Security', 'Cloud Security'), ('Proteção da Infraestrutura', 'Proteção da Infraestrutura'), ('Gestão de Conformidades', 'Gestão de Conformidades'), ('Gestão de Vulnerabilidades', 'Gestão de Vulnerabilidades'), ('Gestão de Patch', 'Gestão de Patch'), ('Desenvolvimento Seguro', 'Desenvolvimento Seguro'), ('Gestão de Crise e Continuidade do Negócio', 'Gestão de Crise e Continuidade do Negócio'), ('Gestão de Incidentes', 'Gestão de Incidentes'), ('Plano de Backup e Recuperação', 'Plano de Backup e Recuperação'), ('SOC', 'SOC'), ('Conscientização', 'Conscientização')], max_length=255),
        ),
    ]
